apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo-deployment
  labels:
    app: docker-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-demo
  template:							
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
      - name: docker-demo
        image: harbor.rkyao.com/rkyao/docker-demo:latest
        imagePullPolicy: Always
        envFrom:
            - configMapRef:
                name: my-config
        ports:
        - containerPort: 8090
      imagePullSecrets:
      - name: myhub
---
apiVersion: v1
kind: Service
metadata:
  name: docker-demo-service
  labels:
    app: docker-demo
spec:
  type: NodePort
  ports:
    - port: 8090
      nodePort: 30001
      targetPort: 8090
  selector:
    app: docker-demo
